# air.toml

root = "."
tmp_dir = "tmp"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", "node_modules", ".git"]
exclude_file = []
delay = 500
log = "stdout"
color = "auto"
clean_on_exit = true

[build]
cmd = "go build -o tmp/main main.go"
bin = "tmp/main"
full_bin = true
exclude_regex = ".*_test.go"
include_ext = ["go"]
send_interrupt = true

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[proxy]
enabled = true              # Enable the proxy feature
bind_addr = "0.0.0.0"       # Bind to all interfaces
port = 8080                 # Proxy listens on this port
forward = 8080              # Your app also runs on this port
force_https = false         # No HTTPS in dev mode
refresh_interval = 500      # How often to retry connection to your app (ms)
fallback_content = "Reloading... Please wait."  # Message served during rebuild
