# Stage 1: Build stage
FROM golang:alpine3.21

# Set Environment Variables
ENV CGO_ENABLED=1

# Set the working directory
WORKDIR /app

# Configure Air Dependencies
RUN go install github.com/air-verse/air@latest

# Copy and download dependencies
RUN apk add --no-cache build-base
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# CMD or ENTRYPOINT command
ENTRYPOINT ["air"]