# Stage 1: Build stage
FROM golang:alpine3.21

# Install C compiler and other build tools early
RUN apk add --no-cache build-base

# Set Environment Variables
ENV CGO_ENABLED=1

# Set the working directory
WORKDIR /app

# Configure Air Dependencies
RUN go install github.com/air-verse/air@v1.61.7

# Copy and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# CMD or ENTRYPOINT command
ENTRYPOINT ["air"]