services:
  app:
    container_name: go-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: go-api:dev
    volumes:
      - ./:/app
      - go-mod-cache:/go/pkg/mod  # optional: cache modules
    ports:
      - "8080:8080"
    environment:
      - AIR_ENV=development
    command: ["air"]
    working_dir: /app
    restart: unless-stopped

volumes:
  go-mod-cache: